In [1]:
!curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.11.1 x86_64-unknown-linux-gnu
installing to /home/codespace/.local/bin
  uv
  uvx
everything's installed!

In [2]:
!uv self update

info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

# Creating virtual enviroment

    1  uv venv env
    2  source env/bin/activate
    3  uv pip install ipykernel
    4  python -m ipykernel install --user --name=env

In [4]:
!uv pip install numpy

Using Python 3.12.1 environment at: env
Checked 1 package in 1ms

In [3]:
!uv pip install pandas

Using Python 3.12.1 environment at: env
Checked 1 package in 2ms

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [7]:
date = pd.date_range("20260102",periods=6)
date

DatetimeIndex(['2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05',
               '2026-01-06', '2026-01-07'],
              dtype='datetime64[us]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list("ABCD"))
df

                   A         B         C         D
2026-01-02 -0.243800  0.854366  1.147183 -1.084087
2026-01-03  0.442807 -0.448095  1.918326 -0.672885
2026-01-04 -0.615592 -1.225979  0.224847 -0.384882
2026-01-05  0.402102  0.912982  2.038963  0.751190
2026-01-06 -0.233701  1.610258 -1.045181 -1.102065
2026-01-07  0.181182  0.026929  0.381134  1.459661

In [12]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20260326"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo"
    }
)
df2

     A          B    C  D      E    F
0  1.0 2026-03-26  1.0  3   test  foo
1  1.0 2026-03-26  1.0  3  train  foo
2  1.0 2026-03-26  1.0  3   test  foo
3  1.0 2026-03-26  1.0  3  train  foo